version: '3'
services:
    express:
        build:
            context: . 
            dockerfile: Dockerfile
        image: fe_test_image:local
        container_name: fe_test_container01
        restart: always
        ports:
            - "8080:8080"
        volumes:
            - ./:/fe_test
            - /fe_test/node_modules
